[versions]
amazonSoftwareVersion = "2.40.1"
apacheLoggingVersion = "2.25.2"
bouncyCastleVersion = "1.83"
junitVersion = "6.0.0"
keycloakVersion = "26.4.7"

[libraries]
comAmazonaws-awsLambdaJavaCore = "com.amazonaws:aws-lambda-java-core:1.4.0"
comAmazonaws-awsLambdaJavaEvents = "com.amazonaws:aws-lambda-java-events:3.16.1"
comAmazonaws-awsLambdaJavaLog4j2 = "com.amazonaws:aws-lambda-java-log4j2:1.6.0"
softwareAmazonAwssdk-cognitoidentityprovider = { group = "software.amazon.awssdk", name = "cognitoidentityprovider", version.ref = "amazonSoftwareVersion" }
softwareAmazonAwssdk-ssm = { group = "software.amazon.awssdk", name = "ssm", version.ref = "amazonSoftwareVersion" }
softwareAmazonAwscdk-awsCdkLib = "software.amazon.awscdk:aws-cdk-lib:2.221.1"
softwareConstructs-constructs = "software.constructs:constructs:10.4.2"
comFasterxmlJacksonDataformat-jacksonDataformatYaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.20.1"
orgApacheLoggingLog4j-log4jCore = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "apacheLoggingVersion" }
orgApacheLoggingLog4j-log4jApi = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "apacheLoggingVersion" }
orgBouncycastle-bcprovJdk18on = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncyCastleVersion" }
orgBouncycastle-bcpkixJdk18on = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncyCastleVersion" }
orgJunitJupiter-junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitVersion" }
orgJunitJupiter-junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitVersion" }
orgJunitJupiter-junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitVersion" }
orgJunitPlatform-junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitVersion" }
orgJetbrains-annotations = "org.jetbrains:annotations:26.0.2-1"
orgKecloak-keycloakSamlCore = { group = "org.keycloak", name = "keycloak-saml-core", version.ref = "keycloakVersion" }
orgKecloak-keycloakServices = { group = "org.keycloak", name = "keycloak-services", version.ref = "keycloakVersion" }
orgMockito-mockitoCore = "org.mockito:mockito-core:5.20.0"
